### ISSUE TITLE
Front-End navbar suivre cahier des charges.

### ISSUE THREAD

**Issue by lea-nova** [lea-nova/bio_bloom_market#9]

**Comment by lea-nova** [comment]
![Image](https://github.com/user-attachments/assets/cb316c2b-172e-40a0-b9f2-e7aa10c47d00)

**Comment by lea-nova** [comment]
# Couleurs pour la Navbar
## Arrière-plan principal de la navbar :
- [ ]  Gris clair (#E0E0E0) ou Blanc neige (#FFFFFF)  ( couleur à définir plus tard )

## Texte des liens (Liens de navigation) :	
- [ ] Couleur standard : #333333 (Gris foncé) pour une lisibilité optimale.
- [ ] 	Couleur au survol : Vert nature (#4CAF50), transition fluide sur le changement de couleur.

## Bouton CTA :	
- [ ]  Fond : Vert nature (#4CAF50).
- [ ] Texte : Blanc neige (#FFFFFF)

**Comment by lea-nova** [comment]
```
 colors: {
        primary: {
          default: '#4CAF50',
          light: '#81C784',
          dark: '#388E3C',
          accent: '#8E9A52',
        },
        secondary: {
          default: '#795548',
          light: '#D7CCC8',
          dark: '#5D4037',
          accent: '#A1887F',
        },
        tertiary: {
          light: '#e0e0e0', // gris clair
          default: '#BDBDBD',
          accent: '#CFD8DC',
          dark: '#757575',
        },
        light: {
          default: '#FFFFFF',
          dark: '#FFFAF0',
          muted: '#F5F5F5',
          accent: '#E3F2FD',
        },
        warning: {
          default: '#FFB74D',
          light: '#FFF9C4'
        }
      },
```
